spring.application.name=room-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/khaaliroom_room
spring.datasource.username=postgres
spring.datasource.password=Dharmu@1996
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info

# JWT
jwt.secret=change-this-to-a-long-random-secret-key
jwt.expiration=3600000